language: node_js
node_js:
- '0.10'
- '0.11'
before_script:
- npm install -g bower grunt-cli
- bower install
services: mongodb
deploy:
  provider: openshift
  user: stramel@gecentral.net
  password:
    secure: GoSlxubt4OGnz+RrKqMFcJpXWVnYTLyQSr8mp3cOfquOjeByQRDipFgkrkRdfNYdZTv+XiY/bmwkXwASmOSIErvzOwVOEDmzENZXx49LKjKKaCqyFc42K5F4JTJltbeLI9BDRRYrvyd4w6zi4hoEg7E7DN/QtMzacM1+4urF3MVqt4Di1snzEYFT2fgkdJjKD20107rwI8Trq1TZ+UCI+GLnFQ15v+JYbw13e5m0wsGe5mNsd+2XpI9LAI6HP+o8MiAzAs7PhIoVExC/6V3/4TxdkTxiG5fixzE6SKyuLrIuqEz8WpOXUBTF0nWlO6SqKDpwJi+W0LpzZV0ObjX6IDOsJF8tzlPGg+Vxbqn9yPQz6G8oWzIhIrjy37O/WjuEkJr6r0vYmn6xnNz/gpfJp1qiJLWmoH7AMoZ+PV8YK5lu6VJ0g99OvLQqsC7gZWDhtdpdrUgCPsPaJiLBzGLgxh1RgIsXYPQ9puOBDFQbU0gO6im1lDh3G37RFeu7RE29VgtFDV53r+Sl30nFigFFNnZkVNYvaiQKnd/m8SAnuE+AceIQjLN7hZI9s/B808CFAOxBXw7cQsyVjlSX8gC6LlaZAApU0AXnfDu1vRSXJn7M5Qn81LEfb98jtIU8hDngQ+UOnOowe5qFoePVbJDq4DGQJzChJmXJ5vTa6aRBF00=
  app: charted
  domain: gh4
  on:
    repo: Hackception/Widgetception
