language: node_js
node_js:
- '0.10'
- '0.11'
before_script:
- npm install -g bower grunt-cli
- bower install
after_success:
- test ${TRAVIS_BRANCH} = master && grunt buildcontrol:openshift
services: mongodb
